### ISSUE TITLE
projecting PC dataset to ASF grid w/ different time dims

### ISSUE THREAD

**Issue by e-marshall** [e-marshall/sentinel1_rtc#3]
In dataset_comparison.ipynb
handling different spatial resolutions section:

fix issue that arises when trying to mask out the NaN values in the ASF dataset in the PC dataset 
code looks like: 
```pc_downsample = pc_subset.interp_like(asf_subset)
pc_mask = xr.where(asf_short.notnull(), pc_downsample,np.nan)
```
end up with a 4-d array with (x,y, acq_date, time) <-- acq date is the time dim of `asf_subset`

figure out best way to organize dims

**Comment by e-marshall** [comment]
Put some steps I've been trying in a notebook [here](https://notebooksharing.space/view/3d5e795dfbad07185c6196c0899663f3d29519415053c0ff985e012d6e09e8d4#displayOptions=), didn't have time to write out more but will update it and keep working on it later, just thought it was easier to work in this notebook than in the middle of the other one

**Comment by dcherian** [comment]
Right you're running into automatic broadcasting.  This is a [key concept](https://tutorial.xarray.dev/fundamentals/02.3_aligning_data_objects.html) when working with multip[el arrays.

You'll want to rename `acq_date` to `time` so that it's consistent.

**Comment by e-marshall** [comment]
Thanks! I had tried that but wasn't sure if I was on the right track/ hadn't realized that the time of the `time` and `acq_date` dims didn't match exactly so had problems. Think its working now! 
closed on https://github.com/e-marshall/sentinel1_rtc/commit/daa81a7e0b22c9085dc20086bcc1976ae24cd466
