### ISSUE TITLE
handling nodata

### ISSUE THREAD

**Issue by e-marshall** [e-marshall/sentinel1_rtc#8]
getting error trying to use `rio.write_nodata()` to convert nodata value from 0. to nan
        "AttributeError: 'RasterDataset' object has no attribute 'write_nodata'" <-- version issue?

**Comment by snowman2** [comment]
No data values are only able to be set on a DataArray, not on a Dataset.

**Comment by snowman2** [comment]
Reference: https://corteva.github.io/rioxarray/stable/getting_started/nodata_management.html

**Comment by e-marshall** [comment]
Thanks @snowman2 ! i'll work on this
